### ISSUE TITLE
Contributor emails appear in clear

### ISSUE THREAD

**Issue by bmispelon** [glasnt/dceu2022-sprints-hack#3]
Hi,

One of the main reasons why I decided to take the old JSON RPC API offline was because I noticed it would leak clear email addresses in fields like author, CC, ... On the website, Trac will automatically obfuscate email address but the API would not do that.

It seems your data has a similar issue and looking for `@` in the notebook seems to bring up several email addresses which as far as I know were not consented to be shared publicly like this.

It's not a huge deal I think, but is that something that could be fixed?

**Comment by glasnt** [comment]
Thanks for the report, @bmispelon. This was my first time working with notebooks in GitHub, but since this repo has a very small amount of commits, I should be able to just scrub all history to correct for this. I'll also update the top of the notebook to note this API doesn't work any more, but I'll keep the code around (just not the output) as a hint for others in the future to help with this sort of work.

**Comment by glasnt** [comment]
This has been completed.

**Comment by bmispelon** [comment]
Amazing, thanks for the quick turnaround on this 👍🏻 .

I've checked and can confirm that the email addresses are gone, all good ✅
